name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest, windows-latest

    if: github.event.workflow_run.conclusion == 'success'
    
    permissions:
      contents: write
    
    steps:
      - name: Download artifact from CI Pipeline
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "patch"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: Release automática gerada pela pipeline de CI/CD.
          files: '*.jar'